name: Bug report
description: Create a bug report to help us track and resolve issues in Rainbow
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for Rainbow! Fill out the following form to your best ability to help us fix the problem.
        Only use this if you're absolutely sure that you found a bug and can reproduce it consistently. For anything else, please use the `#custom-resource-packs` channel on [our Discord server](https://discord.gg/geysermc).
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce this behaviour.
      placeholder: |
        1. Set up a Java resourcepack with '...'
        2. Load the pack in Rainbow and map item '...'
        3. Map block '...'
        4. Finish the pack and load it on Bedrock
        5. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: upload
    attributes:
      label: Your `report.txt` file
      description: If Rainbow was able to generate a `report.txt` file, please upload it here.
    validations:
      accept: .txt
  - type: upload
    attributes:
      label: Screenshots/videos
      description: Preferably add screenshots or videos, both of the expected behaviour (likely on Java), and the behaviour seen (likely on Bedrock), to help explain your problem.
    validations:
      accept: ".png,.jpg,.jpeg,.gif,.svg,.webp,.mp4,.mov,.webm"
  - type: upload
    attributes:
      label: Resourcepacks used
      description: To make reproducing and resolving this bug easier, you can upload a Java resourcepack here that can be used to replicate the issue. When you do, preferably include only the content necessary to replicate the bug. Uploading the Bedrock resourcepack generated by Rainbow can also help!
    validations:
      accept: .zip
  - type: input
    attributes:
      label: Rainbow version
      description: What version of Rainbow are you running?
      placeholder: "For example: 0.2.0-26.1-b53"
    validations:
      required: true
  - type: input
    attributes:
      label: "Minecraft: Bedrock Edition Device/Version"
      description: "What version of Minecraft: Bedrock Edition are you using, and what device(s) does the bug occur on?"
      placeholder: "For example: 26.20, Windows"
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
